http://127.0.0.1:8000/products

###
http://127.0.0.1:8000/products?search=need

###
http://127.0.0.1:8000/products?order_by=생성일

###
http://127.0.0.1:8000/products?order_by=총펀딩금액

###
POST  http://127.0.0.1:8000/products/ 
Content-Type: application/json

{
    "title": "need punding",
    "publisher_name": "gyujae",
    "description": "hello my name is need punding",
    "target_amount": 10000,
    "funding_end_date": "2022-04-4",
    "one_time_funding_amount": 500
}

###

http://127.0.0.1:8000/products/1
###

http://127.0.0.1:8000/products/7

###
PATCH  http://127.0.0.1:8000/products/2/
content-type: application/json

{
    "title": "Hello Title"
}

###
DELETE http://127.0.0.1:8000/products/4/