http://127.0.0.1:8000/products

###
http://127.0.0.1:8000/products?search=first

###
POST  http://127.0.0.1:8000/products/ 
Content-Type: application/json

{
    "title": "api make product2",
    "publisher_name": "gyujae",
    "description": "this is my product from api http2",
    "target_amount": 10000,
    "funding_end_date": "2022-04-10",
    "one_time_funding_amount": 500
}

###

http://127.0.0.1:8000/products/1
###

http://127.0.0.1:8000/products/2

###
PATCH  http://127.0.0.1:8000/products/2/
content-type: application/json

{
    "title": "Update Title"
}

###
DELETE http://127.0.0.1:8000/products/4/