http://127.0.0.1:8000/products
Authorization: Basic gyujae:1

###
http://127.0.0.1:8000/products?search=need

###
http://127.0.0.1:8000/products?order_by=생성일

###
http://127.0.0.1:8000/products?order_by=총펀딩금액

###
POST  http://127.0.0.1:8000/products/ 
Content-Type: application/json
Authorization: Basic gyujae:1

{
    "title": "hello hwi",
    "description": "name gear asdasdas",
    "target_amount": 1000,
    "funding_end_date": "2022-04-20",
    "one_time_funding_amount": 200
}

###

http://127.0.0.1:8000/products/1
###

http://127.0.0.1:8000/products/2

###
PATCH  http://127.0.0.1:8000/products/2/
content-type: application/json

{
    "title": "Hello Title",
    
}

###
DELETE http://127.0.0.1:8000/products/4/

###
http://127.0.0.1:8000/users/

###
POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
    "username": "gyutae",
    "password": "1",
    "email": "rbxo@naver.com"
}

###
http://127.0.0.1:8000/users/2


###
PATCH http://127.0.0.1:8000/users/2/
Content-Type: application/json

{
    "username": "iksu"
}

###
DELETE http://127.0.0.1:8000/users/2/