# Generated by Django 3.2.12 on 2022-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('publisher_name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('target_amount', models.IntegerField(editable=False)),
                ('funding_end_date', models.DateField()),
                ('one_time_funding_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
