# Generated by Django 3.2.12 on 2022-04-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_target_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
