# Generated by Django 3.2.12 on 2022-04-06 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_product_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='participants_count',
        ),
        migrations.AddField(
            model_name='product',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
