# Generated by Django 3.2.12 on 2022-04-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_total_amout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_amout',
            new_name='total_amount',
        ),
    ]
