# Generated by Django 3.2.12 on 2022-04-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_total_amout_product_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
